default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#Feel Free to change the username and password to match your local postgres env
development:
  <<: *default
  database: recipe_development
  username: shawn
  password: test1
  port: 5432
  host: localhost

#Feel Free to change the username and password to match your local postgres env
test:
  <<: *default
  database: recipe_test
  username: shawn
  password: test1
  port: 5432
  host: localhost


production:
  url: <%= ENV['DATABASE_URL'] %>